# Generated by Django 5.1.3 on 2024-11-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensors',
            name='sensor_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
