# Generated by Django 5.1.3 on 2024-11-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sensors_sensor_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensors',
            name='serial_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
