# Generated by Django 5.1.3 on 2024-11-17 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sensortype_usersensor_delete_sensors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensortype',
            name='sensor_name',
            field=models.CharField(help_text='Назва типу сенсора', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='serial_number',
            field=models.CharField(editable=False, help_text='Унікальний серійний номер', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='usersensor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата і час додавання сенсора'),
        ),
        migrations.AlterField(
            model_name='usersensor',
            name='name',
            field=models.CharField(help_text="Користувацька назва сенсора (наприклад, 'Датчик на кухні')", max_length=50),
        ),
        migrations.AlterField(
            model_name='usersensor',
            name='sensor_type',
            field=models.ForeignKey(help_text='Тип сенсора', on_delete=django.db.models.deletion.CASCADE, related_name='user_sensors', to='core.sensortype'),
        ),
        migrations.AlterField(
            model_name='usersensor',
            name='user',
            field=models.ForeignKey(help_text='Користувач, який додав сенсор', on_delete=django.db.models.deletion.CASCADE, related_name='user_sensors', to=settings.AUTH_USER_MODEL),
        ),
    ]
