# Generated by Django 5.1.3 on 2024-11-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sensortype_sensor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersensor',
            name='sensor_value',
            field=models.FloatField(blank=True, help_text='Значення сенсора (може бути пустим)', null=True),
        ),
    ]
